name: lines_longer_than
description: the package provides a configurable lint similar to line_longer_than_80_chars.
version: 1.0.0
repository: https://github.com/JakubWijata/line_longer_than
issue_tracker: https://github.com/JakubWijata/line_longer_than/issues

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  custom_lint_builder: ^0.5.0
  source_gen: ^1.4.0
  analyzer: ^5.12.0
  collection: ^1.17.1
  meta: ^1.9.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  custom_lint: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
